name = "hugotheme"
license = ""
licenselink = ""
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""

[original]
  name = ""
  homepage = ""
  repo = ""
